name: jrocco
favicon: null
layout_spectrum: 0.1358815690036863
typography_spectrum: 0.04783691745251417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5259406922850758
  lightness: 0.7103004790842533
  saturation: 0.7929459910374135
  rhythmicContrast: 0.8717455896548927
purpose: []
