name: jrocco
favicon: null
layout_spectrum: 0.83909
typography_spectrum: 0.27592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1f3484'
    - '#795f8e'
    - '#c2898c'
    - '#e6e3ec'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
