name: A small corner of the web
favicon: null
layout_spectrum: 0.83909
typography_spectrum: 0.37366
title: In a small corner of the web
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1f3484'
    - '#795f8e'
    - '#c2898c'
    - '#e6e3ec'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
