name: jrocco
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1f3484'
    - '#795f8e'
    - '#c2898c'
    - '#e6e3ec'
  brandStrength: 0.6875
  lightness: 0.7103004790842533
  saturation: 0.5
  rhythmicContrast: 0.8717455896548927
purpose: []
